services:
  - type: web
    name: connectafriq
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_TYPE
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: connectafriq-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: connectafriq-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: connectafriq-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: connectafriq-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: connectafriq-db
          property: port

databases:
  - name: connectafriq-db
    plan: free
